require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - spec/spec_helpers.rb
    - spec/rails_helper.rb
    - node_modules/**/*